[build]
  command = "npm ci && npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20.11.1"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[context.production.environment]
  NODE_ENV = "production"